Update environment

diff --git a/bin/devcontainer b/bin/devcontainer
--- a/bin/devcontainer
+++ b/bin/devcontainer
@@ -9,7 +9,7 @@ cd "${ROOT}"
 # Load common functions
 source ./bin/_common
 
-dk=$(which docker) || die "ERROR: Docker not found."
+docker=$(which docker) || die "ERROR: Docker not found."
 
 workspace=${PWD##*/}
 workdir="/workspaces/${workspace}"
@@ -21,26 +21,26 @@ volume="${ROOT}:${workdir}"
 
 cmd="${1:-menu}"
 
-dk_start() {
+docker_start() {
     tmp=$(echo "${port}" | cut -d":" -f-2)
-    tmp=$(${dk} ps | grep "${tmp}" | awk "{print \$NF}")
+    tmp=$(${docker} ps | grep "${tmp}" | awk "{print \$NF}")
     if [ -n "${tmp}" ] ; then
         log.info "Stop container ${tmp}..."
-        ${dk} stop "${tmp}"
+        ${docker} stop "${tmp}"
     fi
 
     log.info "Start container..."
-    ${dk} start "${container}"
+    ${docker} start "${container}"
 }
 
-if ! ${dk} ps -a | grep -wq ${container} && [[ "${cmd}" != "down" ]]; then
+if ! ${docker} ps -a | grep -wq ${container} && [[ "${cmd}" != "down" ]]; then
     log.info "Create container..."
-    ${dk} create -it --name "${container}" -p "${port}" -v "${volume}" "${image}"
+    ${docker} create -it --name "${container}" -p "${port}" -v "${volume}" "${image}"
 
-    dk_start
+    docker_start
 
     log.info "Initialize container..."
-    ${dk} exec -it -w "${workdir}" "${container}" container install
+    ${docker} exec -it -w "${workdir}" "${container}" container install
 fi
 
 if [[ "${cmd}" == "menu" ]]; then
@@ -74,28 +74,28 @@ fi
 case "${cmd}" in
     "stop" )
         log.info "Stop container..."
-        ${dk} stop "${container}"
+        ${docker} stop "${container}"
         ;;
     "down" )
         log.info "Destroy container..."
-        ${dk} stop -t 10 "${container}" >/dev/null
-        ${dk} rm "${container}"
+        ${docker} stop -t 10 "${container}" >/dev/null
+        ${docker} rm "${container}"
         ;;
     "bash" )
-        if ! ${dk} ps | grep -wq ${container}; then
-            dk_start
+        if ! ${docker} ps | grep -wq ${container}; then
+            docker_start
         fi
         log.info "Interactive mode..."
-        ${dk} exec -it "${container}" bash
+        ${docker} exec -it "${container}" bash
         ;;
     * )
-        if ! ${dk} ps | grep -wq ${container}; then
-            dk_start
+        if ! ${docker} ps | grep -wq ${container}; then
+            docker_start
         fi
         log.info "Send command '${cmd}' to container..."
         if [[ "${cmd}" == "start" ]]; then
             log.info "After Home Assistant initialization you can access to system on http://localhost:9123/"
         fi
-        ${dk} exec -it -w "${workdir}" "${container}" container "${cmd}"
+        ${docker} exec -it -w "${workdir}" "${container}" container "${cmd}"
         ;;
 esac
